version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ApiBiblioteca
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER:  ${DB_USER}
    ports:
      - '5431:5432'