spring:
  application:
    name: api-biblioteca
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: library-db-pool
      max-lifetime: 600000
      connection-timeout: 100000
  jpa:
    show-sql: true
